### PR TITLE
GPU stable up to 1246Mhz

### PR DESCRIPTION
**Pull request by SharkEzz**
Set max GPU frequency to 1246 Mhz instead of 1146 Mhz.
After several tests, this frequency seems to be stable with the voltage used !

### CODE REVIEW

**Comment by ananjaser1211** [comment]
Interesting, i stopped trying higher clocks at 1146 MHz. i hope you can let me know how is the battery performance overall. as GPU CPU OC is a bit taxing on this phone (i personally use it at 1146 mhz and max CPU with max brightness through out a day, and still manages to stay powered on.

**Comment by SharkEzz** [comment]
I think battery backup will be almost identical with a frequency of 1146 Mhz because the voltage used is the same but I will do some tests by lowering the voltage slightly.
However, I observe a notable performance gain!
I will do some tests about battery backup and I will report as soon as possible!

**Comment by ananjaser1211** [comment]
Awesome, appreciate the contributions. if you had time maybe you can try and see if we can boot on 1.8ghz. ive pushed +50mV without success, but i may have overlooked something, this is the first time im OCing

**Comment by SharkEzz** [comment]
So, I tried for 2 days to see the impact of the GPU overclock on the battery and there is no suspicious battery drain to report.
However, I compared the voltage used by the Exynos 7880 (the big brother of the 7870) and saw that it used the same GPU voltages up to about 1001 MHz.
After some tests I managed to not overvolt the GPU and keep it stable at 1146 MHz with the base voltage (e1a310ac7ea0516751253d6fb4073d32ca430328)
For the CPU overclock, I am unable to set a frequency higher than the current one (1.7 Ghz), Android always reports a frequency of 1.7 Ghz and does not change with the one I defined in the file "exynos7870.dtsi" and "exynos7870-j5y17lte_common.dtsi". Did I miss something ? An idea for that would be welcome!

**Comment by ananjaser1211** [comment]
Nice findings, this weekend ill merg pull requests. regarding CPU

You need to adjust

`-		cl0_max_support_idx = <1>;
 +		cl0_max_support_idx = <2>;
  		cl0_min_support_idx = <16>;
 -		cl0_boot_max_qos = <1924000>;
 +		cl0_boot_max_qos = <1794000>;`

Adjust the bootmax Qos and max support IDX

**Review by ananjaser1211 — APPROVED** [review]

**Pull request merged**
